### ISSUE TITLE
Can't load 

### ISSUE THREAD

**Issue by CupidonSauce173** [PotatoeTrainYT/BookHelp#3]
[Server thread/CRITICAL] : ParseError: ¨syntax error, unexpected '$book' (T_VARABLE)¨ (EXCEPTION) in ¨BookHelp-master/src/BookHelp/Main¨ at line 48

Line : $book->setAuthor($config->get("author"));

Result : Plugin can't load

How to repeat this issue : 
1.Drop the plugin on the plugin directory.
2.Start the server.

**Comment by PotatoeTrainYT** [comment]
https://github.com/PotatoeTrainYT/BookHelp/commit/2904307b4523410d097de22d78ebaf29129e748a
